name = "Tensura: Reincarnated NixOS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bce9a8aa8182a29d813c7c2c033fbaf6df01b56d39c3e0dcb49a0c0de2e43e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
