name = "Tensura-Nix"
author = "ShiniDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dc242a0ef6cf085a369b5825b722cc70aaf0c0358aa6cefa0f9b29c23fb675f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
