name = "Tensura-Nix"
author = "ShiniDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "983e9dbf253d05326eb2009eee7e528cd60ee7e4ce907f52631c3c152d6d4043"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
